Try the full configure script.

diff --git a/packages/brew-debug/brew-debug.0.0.1/files/configure b/packages/brew-debug/brew-debug.0.0.1/files/configure
--- a/packages/brew-debug/brew-debug.0.0.1/files/configure
+++ b/packages/brew-debug/brew-debug.0.0.1/files/configure
@@ -349,3 +349,92 @@ if test "$gmp" = 'gmp' -o "$gmp" = 'auto'; then
         fi
     fi
 fi
+if test "$gmp" = 'mpir' -o "$gmp" = 'auto'; then
+    checkinc mpir.h
+    if test $? -eq 1; then
+        checklib mpir
+        if test $? -eq 1; then
+            gmp='OK'
+            cclib="$cclib -lmpir"
+            ccdef="-DHAS_MPIR $ccdef"
+        fi
+    fi
+fi
+if test "$gmp" != 'OK'; then echo "cannot find GMP nor MPIR"; exit 2; fi
+
+
+# OCaml version
+
+ocamlver=`ocamlc -version`
+
+# Extended comparisons available since 3.12.1
+case "$ocamlver" in
+    [12].* | 3.0* | 3.10* | 3.11* | 3.12.0*)
+        ;;
+    *)
+        echo "OCaml extended comparison supported"
+        ccdef="-DZ_OCAML_COMPARE_EXT $ccdef"
+        ;;
+esac
+
+# New hash functions available since 4.00.0
+case "$ocamlver" in
+    [123].*)
+        ;;
+    *)
+        echo "OCaml new hash functions available"
+        ccdef="-DZ_OCAML_HASH $ccdef"
+        ;;
+esac
+
+# dump Makefile
+
+cat > Makefile <<EOF
+# generated by ./configure
+
+CC=$cc
+OCAMLC=$ocamlc
+OCAMLOPT=$ocamlopt
+OCAMLDEP=$ocamldep
+OCAMLMKLIB=$ocamlmklib
+OCAMLDOC=$ocamldoc
+OCAMLFLAGS=$mlflags
+OCAMLOPTFLAGS=$mloptflags
+OCAMLINC=$mlinc
+CFLAGS=$ccinc $ccdef $ccopt
+ASFLAGS=$ccdef $asopt
+LIBS=$cclib
+ARCH=$arch
+INSTALLDIR=$installdir
+AR=$ar
+INSTALL=install
+OCAMLFIND=ocamlfind
+INSTMETH=$instmeth
+OBJSUFFIX=$objsuffix
+HASOCAMLOPT=$hasocamlopt
+HASDYNLINK=$hasdynlink
+
+include project.mak
+EOF
+
+
+# dump summary
+
+cat <<EOF
+
+detected configuration:
+
+  native-code:          $hasocamlopt
+  dynamic linking:      $hasdynlink
+  asm path:             $arch
+  defines:              $ccdef
+  libraries:            $cclib
+  C options:            $ccopt
+  asm options           $asopt
+  installation path:    $installdir
+  installation method   $instmeth
+
+configuration successful!
+now type "make" to build
+then type "make install" or "sudo make install" to install
+EOF
