Elaborate on final 'build failed' message

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -117,7 +117,7 @@ jobs:
             Write-Host
           }
           if ($failed) {
-            throw "build failed"
+            throw "One or more packages failed to build"
           }
           Exit
 
@@ -235,5 +235,5 @@ jobs:
             esac
           done
           if [ "$failed" = true ] ; then
-            echo "build failed" && exit 1
+            echo "One or more packages failed to build" && exit 1
           fi
